
-- 1. Tournaments Table
create table tournaments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  date text not null,
  time text not null,
  description text,
  data jsonb -- Stores internal data like groups, bracket, config options
);

-- 2. Users Table (New)
create table users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  first_name text not null,
  last_name text,
  email text unique not null,
  phone text
);

-- 3. Registrations Table
create table registrations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tournament_id bigint references tournaments(id) on delete cascade not null,
  
  -- Foreign keys to users table
  player1_id bigint references users(id),
  player2_id bigint references users(id),
  
  -- Legacy fields (optional, if you want to keep data for old records not linked to users, otherwise can be removed)
  player1_name text,
  player1_phone text,
  player2_name text,
  player2_phone text,

  category text,
  status text default 'pending' -- 'pending', 'approved', 'rejected'
);

-- 4. Enable Row Level Security (RLS)
alter table tournaments enable row level security;
alter table users enable row level security;
alter table registrations enable row level security;

-- 5. Create Policies (Public Access for Development)
-- Tournaments
create policy "Public tournaments access" on tournaments for select using (true);
create policy "Public tournaments insert" on tournaments for insert with check (true);
create policy "Public tournaments update" on tournaments for update using (true);
create policy "Public tournaments delete" on tournaments for delete using (true);

-- Users
create policy "Public users access" on users for select using (true);
create policy "Public users insert" on users for insert with check (true);
create policy "Public users update" on users for update using (true);

-- Registrations
create policy "Public registrations access" on registrations for select using (true);
create policy "Public registrations insert" on registrations for insert with check (true);
create policy "Public registrations update" on registrations for update using (true);
create policy "Public registrations delete" on registrations for delete using (true);
